ALTER TABLE Person ADD Person_FK_RECURSIVE_1 NUMBER(10);

ALTER TABLE Person
  ADD CONSTRAINT FK_CONSTR_Person_RECURSIVE_1
  FOREIGN KEY (Person_FK_RECURSIVE_1)
  REFERENCES Person(Person_ID);


ALTER TABLE Person ADD Person_FK_RECURSIVE_2 NUMBER(10);

ALTER TABLE Person
  ADD CONSTRAINT FK_CONSTR_Prson_RECURSIVE_2
  FOREIGN KEY (Person_FK_RECURSIVE_2)
  REFERENCES Person(Person_ID);
  
ALTER TABLE Project ADD Repository_FK NUMBER(10);

ALTER TABLE Project
  ADD CONSTRAINT FK_CONSTR_Repository
  FOREIGN KEY (Repository_FK)
  REFERENCES Repository(Repository_ID);

ALTER TABLE Project ADD Person_FK NUMBER(10);

ALTER TABLE Project
  ADD CONSTRAINT FK_CONSTR_Person
  FOREIGN KEY (Person_FK)
  REFERENCES Person(Person_ID);

ALTER TABLE WorkItem ADD Project_FK NUMBER(10);

ALTER TABLE WorkItem
  ADD CONSTRAINT FK_CONSTR_Project
  FOREIGN KEY (Project_FK)
  REFERENCES Project(Project_ID);

ALTER TABLE FileAttachement ADD WorkItem_FK NUMBER(10);

ALTER TABLE FileAttachement
  ADD CONSTRAINT FK_CONSTR_WorkItem
  FOREIGN KEY (WorkItem_FK)
  REFERENCES WorkItem(WorkItem_ID);
