package org.whole.crossexamples.mps.theSimplestLanguage;


/**
 *  Generated by Whole
 */
public class MyHelloWorld {

    public MyHelloWorld() {
    }

    public static void main(String[] args) {
        System.out.println("hello world");
    }
}
